# Generated by Django 6.1.1 on 2026-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.CharField(default='🍽️', max_length=10),
        ),
    ]
