# Generated by Django 6.1.1 on 2026-09-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_category_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='emoji',
            field=models.CharField(default='🥕', max_length=10),
        ),
    ]
